version: '2'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - backend
  auth:
    build: ./auth
    expose:
      - "5052"
    networks:
      - backend
    depends_on:
      - redis
  biz:
    build: ./biz
    expose:
      - "5062"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
  gateway:
    build: ./gateway
    expose:
      - "6433"
    networks:
      - backend
  redis:
    image: redis
    expose:
      - "6379"
    networks:
      - backend
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - ./sql/web_hw1.sql:/docker-entrypoint-initdb.d/web_hw1.sql
      - ./db:/var/lib/postgresql/data

volumes:
  db:

networks:
  backend:
    name: backend-network
