// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: grpc/biz-server.proto

package biz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKey   int32 `protobuf:"varint,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	MessageId int32 `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *UserAuth) Reset() {
	*x = UserAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_biz_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuth) ProtoMessage() {}

func (x *UserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_biz_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuth.ProtoReflect.Descriptor instead.
func (*UserAuth) Descriptor() ([]byte, []int) {
	return file_grpc_biz_server_proto_rawDescGZIP(), []int{0}
}

func (x *UserAuth) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserAuth) GetAuthKey() int32 {
	if x != nil {
		return x.AuthKey
	}
	return 0
}

func (x *UserAuth) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type UsersList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users     []int32 `protobuf:"varint,1,rep,packed,name=users,proto3" json:"users,omitempty"`
	MessageId int32   `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *UsersList) Reset() {
	*x = UsersList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_biz_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersList) ProtoMessage() {}

func (x *UsersList) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_biz_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersList.ProtoReflect.Descriptor instead.
func (*UsersList) Descriptor() ([]byte, []int) {
	return file_grpc_biz_server_proto_rawDescGZIP(), []int{1}
}

func (x *UsersList) GetUsers() []int32 {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UsersList) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_grpc_biz_server_proto protoreflect.FileDescriptor

var file_grpc_biz_server_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x69, 0x7a, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x62, 0x69, 0x7a, 0x22, 0x5e, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x32,
	0x78, 0x0a, 0x0a, 0x62, 0x69, 0x7a, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2c, 0x0a,
	0x09, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x0f, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x19, 0x67,
	0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x73, 0x71,
	0x6c, 0x5f, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x0f, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x62, 0x69, 0x7a,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_biz_server_proto_rawDescOnce sync.Once
	file_grpc_biz_server_proto_rawDescData = file_grpc_biz_server_proto_rawDesc
)

func file_grpc_biz_server_proto_rawDescGZIP() []byte {
	file_grpc_biz_server_proto_rawDescOnce.Do(func() {
		file_grpc_biz_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_biz_server_proto_rawDescData)
	})
	return file_grpc_biz_server_proto_rawDescData
}

var file_grpc_biz_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_biz_server_proto_goTypes = []interface{}{
	(*UserAuth)(nil),  // 0: biz.user_auth
	(*UsersList)(nil), // 1: biz.users_list
}
var file_grpc_biz_server_proto_depIdxs = []int32{
	0, // 0: biz.biz_server.get_users:input_type -> biz.user_auth
	0, // 1: biz.biz_server.get_users_with_sql_inject:input_type -> biz.user_auth
	1, // 2: biz.biz_server.get_users:output_type -> biz.users_list
	1, // 3: biz.biz_server.get_users_with_sql_inject:output_type -> biz.users_list
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_biz_server_proto_init() }
func file_grpc_biz_server_proto_init() {
	if File_grpc_biz_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_biz_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_biz_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_biz_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_biz_server_proto_goTypes,
		DependencyIndexes: file_grpc_biz_server_proto_depIdxs,
		MessageInfos:      file_grpc_biz_server_proto_msgTypes,
	}.Build()
	File_grpc_biz_server_proto = out.File
	file_grpc_biz_server_proto_rawDesc = nil
	file_grpc_biz_server_proto_goTypes = nil
	file_grpc_biz_server_proto_depIdxs = nil
}
